#ifndef _PROPERTY_LIST_H_
#define _PROPERTY_LIST_H_

#define SHOW_INTERESTED_PROPERTIES	1
#define SHOW_DEVICE_PROP			1
#define SHOW_IMG_FORMAT_PROP		1
#define SHOW_ACQUISION_PROP			1

#define GENICAMPROPGETBYNAME(CONTROLLER, NAME) \
do{ \
	std::cout << #NAME << " : " << CONTROLLER.NAME.readS() << std::endl; \
} while (0)

#define DUMPDEVICEPROP(CONTROLLER) \
{ \
	GENICAMPROPGETBYNAME(CONTROLLER, deviceModelName); \
	GENICAMPROPGETBYNAME(CONTROLLER, deviceFirmwareVersion); \
	GENICAMPROPGETBYNAME(CONTROLLER, deviceSerialNumber); \
	GENICAMPROPGETBYNAME(CONTROLLER, deviceTemperature); \
}


#define DUMPIMGFORMATPROP(CONTROLLER) \
{ \
	GENICAMPROPGETBYNAME(CONTROLLER, sensorHeight); \
	GENICAMPROPGETBYNAME(CONTROLLER, sensorWidth); \
	GENICAMPROPGETBYNAME(CONTROLLER, binningHorizontal); \
	GENICAMPROPGETBYNAME(CONTROLLER, binningHorizontalMode); \
	GENICAMPROPGETBYNAME(CONTROLLER, decimationHorizontal); \
	GENICAMPROPGETBYNAME(CONTROLLER, decimationHorizontalMode); \
	GENICAMPROPGETBYNAME(CONTROLLER, decimationVertical); \
	GENICAMPROPGETBYNAME(CONTROLLER, decimationVerticalMode); \
	GENICAMPROPGETBYNAME(CONTROLLER, height); \
	GENICAMPROPGETBYNAME(CONTROLLER, heightMax); \
	GENICAMPROPGETBYNAME(CONTROLLER, width); \
	GENICAMPROPGETBYNAME(CONTROLLER, widthMax); \
	GENICAMPROPGETBYNAME(CONTROLLER, pixelFormat); \
}

#define DUMPACQUISIONPROP(CONTROLLER) \
{ \
	GENICAMPROPGETBYNAME(CONTROLLER, acquisitionMode); \
	GENICAMPROPGETBYNAME(CONTROLLER, acquisitionFrameRate); \
	GENICAMPROPGETBYNAME(CONTROLLER, exposureAuto); \
	GENICAMPROPGETBYNAME(CONTROLLER, exposureMode); \
	GENICAMPROPGETBYNAME(CONTROLLER, exposureTime); \
	GENICAMPROPGETBYNAME(CONTROLLER, mvExposureAutoAverageGrey); \
	GENICAMPROPGETBYNAME(CONTROLLER, mvExposureAutoAOIMode); \
}

#endif